/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-primary": "#ffffff",
        "on-primary-container": "#de757c",
        "surface-dim": "#dcdad4",
        "on-tertiary-fixed-variant": "#4d4547",
        "on-background": "#1c1c18",
        "on-surface": "#1c1c18",
        "surface-container-highest": "#e5e2dc",
        "inverse-primary": "#ffb3b6",
        "outline-variant": "#dbc0c0",
        "on-secondary-fixed-variant": "#5d4202",
        "on-tertiary": "#ffffff",
        "surface-tint": "#9b4149",
        "primary-fixed-dim": "#ffb3b6",
        "surface-bright": "#fcf9f3",
        "on-secondary-fixed": "#271900",
        "surface-variant": "#e5e2dc",
        "on-secondary": "#ffffff",
        "inverse-surface": "#31312d",
        "secondary-fixed": "#ffdea5",
        "tertiary-fixed": "#ecdfe1",
        "outline": "#887272",
        "tertiary": "#1d1718",
        "tertiary-fixed-dim": "#d0c4c6",
        "on-error": "#ffffff",
        "secondary": "#775a1a",
        "on-primary-fixed-variant": "#7d2a33",
        "primary": "#3a000a",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#ffdada",
        "surface-container": "#f0eee8",
        "on-surface-variant": "#554243",
        "surface-container-low": "#f6f3ed",
        "surface": "#fcf9f3",
        "inverse-on-surface": "#f3f0ea",
        "secondary-container": "#fed489",
        "on-tertiary-container": "#9c9294",
        "on-tertiary-fixed": "#201a1c",
        "error": "#ba1a1a",
        "background": "#fcf9f3",
        "secondary-fixed-dim": "#e9c178",
        "on-secondary-container": "#785a1b",
        "error-container": "#ffdad6",
        "surface-container-high": "#ebe8e2",
        "on-primary-fixed": "#40000c",
        "on-error-container": "#93000a",
        "tertiary-container": "#322b2d",
        "primary-container": "#5a0f1b"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "margin-mobile": "1rem",
        "margin-desktop": "2.5rem",
        "space-2xl": "3rem",
        "space-xs": "0.5rem",
        "gutter-mobile": "1rem",
        "space-xl": "2rem",
        "space-2xs": "0.25rem",
        "gutter-tablet": "1.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-3xl": "4rem",
        "gutter-desktop": "2rem"
      },
      "fontFamily": {
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "currency-num": ["Plus Jakarta Sans", "sans-serif"],
        "title-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "display-mobile": ["Playfair Display", "serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "display": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"]
      },
      "fontSize": {
        "body-md": ["14px", { "lineHeight": "22px", "fontWeight": "400" }],
        "currency-num": ["18px", { "lineHeight": "24px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "title-sm": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg-mobile": ["26px", { "lineHeight": "34px", "fontWeight": "600" }],
        "display-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-sm": ["12px", { "lineHeight": "18px", "fontWeight": "400" }],
        "title-md": ["16px", { "lineHeight": "24px", "letterSpacing": "-0.005em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display": ["44px", { "lineHeight": "52px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "26px", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.06em", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
